let questions = [
  {
    section: "Science and Tech",
    numb: 1,
    question: "What does HTML stand for?",
    answer: "Hyper Text Markup Language",
    options: [
      "Hyper Text Preprocessor",
      "Hyper Text Markup Language",
      "Hyper Text Multiple Language",
      "Hyper Text Multi Language",
    ],
  },
  {
    section: "Science and Tech",
    numb: 2,
    question: "What does CSS stand for?",
    answer: "Cascading Style Sheet",
    options: [
      "Common Style Sheet",
      "Colorful Style Sheet",
      "Computer Style Sheet",
      "Cascading Style Sheet",
    ],
  },
  {
    section: "Science and Tech",
    numb: 3,
    question: "What does PHP stand for?",
    answer: "Hypertext Preprocessor",
    options: [
      "Hypertext Preprocessor",
      "Hypertext programming",
      "Hypertext preprogramming",
      "Hypertext preprocessor",
    ],
  },
  {
    section: "Science and Tech",
    numb: 4,
    question: "What does SQL stand for?",
    answer: "Structured Query Language",
    options: [
      "Stylish Question Language",
      "Stylesheet Query Language",
      "Statement Question Language",
      "Structured Query Language",
    ],
  },
  {
    section: "Science and Tech",
    numb: 5,
    question: "What does XML stand for?",
    answer: "Extensible Markup Language",
    options: [
      "Extensible Markup Language",
      "Extensible Multiple Language",
      "Extra Multi Program Language",
      "Examine Multiple Language",
    ],
  },
  {
    section: "Science and Tech",
    numb: 6,
    question: "Which popular company designed the first CPU? ",
    answer: "Intel",
    options: ["Intel", "AMD", "IBM", "Apple"],
  },
  {
    section: "Science and Tech",
    numb: 7,
    question:
      "What game console sold 514,000 units for Sega during its first two weeks in U.S. stores, in 1999? ",
    answer: "Dreamcast",
    options: ["Dreamcast", "Saturn", "Genesis", "Playstation"],
  },
  {
    section: "Science and Tech",
    numb: 8,
    question: "Who coined the term “virtual reality”? ",
    answer: "Jaron Lanier",
    options: ["Jaron Lanier", "William Gibson", "Kevin Kelly", "Alan Turing"],
  },
  {
    section: "Science and Tech",
    numb: 9,
    question:
      "The hottest place in the universe is located in which constellation? ",
    answer: "The constellation Virgo",
    options: ["The constellation Virgo", "Orion", "Andromela", "Centaurus"],
  },
  {
    section: "Science and Tech",
    numb: 10,
    question:
      "How old is the universe in years, plus or minus 1 billion years? ",
    answer: "13.8 billion years old",
    options: [
      "10 billion years old",
      "15 bilion years old",
      "5 billion years old",
      "13.8 billion years old",
    ],
  },
  {
    section: "Science and Tech",
    numb: 11,
    question: "What is the main component of a computer's CPU?",
    answer: "Transistors",
    options: ["Transistors", "Capacitors", "Resistors", "Diodes"],
  },
  {
    section: "Science and Tech",
    numb: 12,
    question: "Which programming language is known as the language of the web?",
    answer: "JavaScript",
    options: ["Python", "Java", "JavaScript", "C++"],
  },
  {
    section: "Food",
    numb: 13,
    question: "What was the first food eaten in space?",
    answer: "Apple sauce",
    options: ["Apple sauce", "Freeze-dried ice cream", "Beef stew", "Tang"],
  },
  {
    section: "Food",
    numb: 14,
    question: "What is the most frequently ordered item of food in the USA?",
    answer: "Fried chicken",
    options: ["Pizza", "Burgers", "Fried chicken", "Tacos"],
  },
  {
    section: "Food",
    numb: 15,
    question:
      "Which fast food outlet has the largest number of restaurants in the world?",
    answer: "Subway",
    options: ["McDonald's", "Subway", "KFC", "Burger King"],
  },
  {
    section: "Food",
    numb: 16,
    question: "Which is the only edible food that never goes bad?",
    answer: "Honey",
    options: ["Salt", "Dried beans", "Soy sauce", "Honey"],
  },
  {
    section: "Food",
    numb: 17,
    question: "How do you know if cranberries are ripe?",
    answer: "They bounce like rubber balls",
    options: [
      "They turn a deep red color",
      "They bounce like rubber balls",
      "They have a sweet smell",
      "They float in water",
    ],
  },
  {
    section: "Food",
    numb: 18,
    question: "What is the most stolen food in the world? ",
    answer: "Cheese",
    options: ["Chocolate", "Bread", "Cheese", "Apples"],
  },
  {
    section: "Food",
    numb: 19,
    question: "What was the first soft drink in space?",
    answer: "Coca Cola",
    options: ["Coca Cola", "Pepsi", "Sprite", "Dr. Pepper"],
  },
  {
    section: "Food",
    numb: 20,
    question: "Which Mexican food has a name meaning “Little Donkey”?",
    answer: "Burrito",
    options: ["Quesadilla", "Enchilada", "Taco", "Burrito"],
  },
  {
    section: "Food",
    numb: 21,
    question: "Which country invented ice cream?",
    answer: "China",
    options: ["Italy", "Greece", "China", "France"],
  },
  {
    section: "Food",
    numb: 22,
    question: "What is the most consumed manufactured drink in the world?",
    answer: "Tea",
    options: ["Coffee", "Orange juice", "Tea", "Soft drinks"],
  },
  {
    section: "Food",
    numb: 23,
    question: "Which nut is used to make marzipan?",
    answer: "Almond",
    options: ["Peanut", "Walnut", "Almond", "Cashew"],
  },
  {
    section: "Food",
    numb: 24,
    question: "What is the main ingredient in guacamole?",
    answer: "Avocado",
    options: ["Tomato", "Onion", "Avocado", "Lime"],
  },
  {
    section: "Nature",
    numb: 25,
    question: "Which gas forms 80% of Earth's atmosphere?",
    answer: "Nitrogen",
    options: ["Oxygen", "Argon", "Nitrogen", "Carbon Dioxide"],
  },
  {
    section: "Nature",
    numb: 26,
    question: "What is a female alligator called?",
    answer: "Cow",
    options: ["Sow", "Gatoress", "Hen", "Cow"],
  },
  {
    section: "Nature",
    numb: 27,
    question: "How many toes does a cat have on each front paw?",
    answer: "Five",
    options: ["Four", "Six", "Five", "Three"],
  },
  {
    section: "Nature",
    numb: 28,
    question: "Which is the fastest moving land snake in the world?",
    answer: "Black Mamba",
    options: ["King Cobra", "Black Mamba", "Pit Viper", "Coral Snake"],
  },
  {
    section: "Nature",
    numb: 29,
    question: "Delphinus delphis is the scientific name for which creature?",
    answer: "Dolphin",
    options: ["Poerpoise", "Dolphin", "Manatee", "Sea Lion"],
  },
  {
    section: "Nature",
    numb: 30,
    question:
      "What country has coastlines on BOTH the Atlantic and Pacific oceans?",
    answer: "Nicaragua",
    options: ["Nicaragua", "Panama", "Chile", "Colombia"],
  },
  {
    section: "Nature",
    numb: 31,
    question:
      "How long could avocados stay ripe on the trees before they die or need to be harvested?",
    answer: "8 months",
    options: ["3 months", "6 months", "8 months", "1 year"],
  },
  {
    section: "Nature",
    numb: 32,
    question: "What is “cynophobia”?",
    answer: "Fear of dogs",
    options: [
      "Fear of cats",
      "Fear of spiders",
      "Fear of clowns",
      "Fear of dogs",
    ],
  },
  {
    section: "Nature",
    numb: 33,
    question: "Banana plants are related to which of the following flowers?",
    answer: "Birds of Paradise",
    options: ["Lilies", "Orchids", "Birds of Paradise", "Tulips"],
  },
  {
    section: "Nature",
    numb: 34,
    question:
      "Saffron, an expensive spice originated from Iran, is derived from which flower?",
    answer: "Crocus",
    options: ["Rose", "Lily", "Crocus", "Sunflower"],
  },
  {
    section: "Nature",
    numb: 35,
    question: "Which animal is known as the 'Ship of the Desert'?",
    answer: "Camel",
    options: ["Elephant", "Camel", "Horse", "Donkey"],
  },
  {
    section: "Nature",
    numb: 36,
    question: "What is the tallest animal in the world?",
    answer: "Giraffe",
    options: ["Elephant", "Giraffe", "Zebra", "Lion"],
  },
  {
    section: "Health",
    numb: 37,
    question: "Which human organ can regenerate itself?",
    answer: "Liver",
    options: ["Liver", "Heart", "Lung", "Skin"],
  },
  {
    section: "Health",
    numb: 38,
    question: "What do doctors look at through an ophthalmoscope?",
    answer: "The eye",
    options: ["The ear", "The throat", "The eye", "The nose"],
  },
  {
    section: "Health",
    numb: 39,
    question: "How much does the average human head weigh?",
    answer: "5kg / 11lbs",
    options: ["3kg / 6.6lbs", "7kg / 15lbs", "4kg / 8.8lbs", "5kg / 11lbs"],
  },
  {
    section: "Health",
    numb: 40,
    question: "What syndrome does SIDS mean to childcare experts?",
    answer: "Sudden Infant Death Syndrome",
    options: [
      "Severe infant Developmental Syndrome",
      "Sudden Infant Death Syndrome",
      "Severe infant Death Syndrome",
      "Sudden infant Disorder Syndrome",
    ],
  },
  {
    section: "Health",
    numb: 41,
    question:
      "Who was the cofounder of modern neurology who greatly influenced a student named Sigmund Freud?",
    answer: "Jean-Martin Charcot",
    options: [
      "Carl Jung",
      "Paul Brocs",
      "Emil Krapelin",
      "Jean-Martin Charcot",
    ],
  },
  {
    section: "Health",
    numb: 42,
    question:
      "What is the full name of the medical scanning technique called PET?",
    answer: "Positron Emission Tomography",
    options: [
      "Positron Emission Tomography",
      "Proton Emission Tomography",
      "Positron Emission Tomography",
      "Physical Emission Tomography",
    ],
  },
  {
    section: "Health",
    numb: 43,
    question:
      "A person with diabetes produces an insufficient amount of what in the body?",
    answer: "Insulin",
    options: ["Glucose", "Insulon", "Hemoglobin", "Insulin"],
  },
  {
    section: "Health",
    numb: 44,
    question:
      "What are the small spots called occasionally seen in your field of vision?",
    answer: "Floaters",
    options: ["Sparks", "Halos", "Floaters", "Shadows"],
  },
  {
    section: "Health",
    numb: 45,
    question: "Which area of the body has the largest bone? ",
    answer: "Leg",
    options: ["Arm", "Spine", "Leg", "Skull"],
  },
  {
    section: "Health",
    numb: 46,
    question: "What is the more common term for odontalgia?",
    answer: "Toothache",
    options: ["Toothache", "Gum disease", "Teethache", "Tooth decay"],
  },
  {
    section: "Health",
    numb: 47,
    question: "What is the largest organ in the human body?",
    answer: "Skin",
    options: ["Liver", "Heart", "Skin", "Lungs"],
  },
  {
    section: "Health",
    numb: 48,
    question: "Which vitamin is produced when a person is exposed to sunlight?",
    answer: "Vitamin D",
    options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"],
  },
  {
    section: "Entertainment",
    numb: 49,
    question:
      "Who was the fictional character Shrek marries in his titular film series?",
    answer: "Princess Fiona",
    options: ["Princess Aurora", "Queen Elsa", "Princess Fiona", "Lady Fiona"],
  },
  {
    section: "Entertainment",
    numb: 50,
    question: "Who is the famous author of the Harry Potter book series?",
    answer: "J.K. Rowling",
    options: ["J.R.R Tolkien", "C.S Lewis", "Suzanne Collins", "J.K. Rowling"],
  },
  {
    section: "Entertainment",
    numb: 51,
    question:
      "What is the name of the courtesan played by Nicole Kidman in Moulin Rouge?",
    answer: "Satine",
    options: ["Roxanne", "Desire", "Lola", "Satine"],
  },
  {
    section: "Entertainment",
    numb: 52,
    question: "Who played park owner John Hammond in Jurassic Park? ",
    answer: "Richard Attenborough",
    options: [
      "Richard Attenborough",
      "Sean Connery",
      "Anthony Hopkins",
      "Michael Caine",
    ],
  },
  {
    section: "Entertainment",
    numb: 53,
    question:
      "In what 1976 thriller does Robert De Niro famously say, “You talkin' to me?” ",
    answer: "Taxi Driver",
    options: ["Raging BUll", "The Godfather", "Taxi Driver", "Goodfellas"],
  },
  {
    section: "Entertainment",
    numb: 54,
    question:
      "What's the name of the anthemic dance near the beginning of The Rocky Horror Picture Show? ",
    answer: "The Time Warp",
    options: ["The Twist", "The Cha-Cha", "The Time Warp", "The Mashed Potato"],
  },
  {
    section: "Entertainment",
    numb: 55,
    question: "What's the name of the skyscraper in Die Hard?",
    answer: "Nakatomi Plaza ",
    options: [
      "Empire State Building",
      "Nakatomi Plaza ",
      "Sears Tower",
      "Wills Tower",
    ],
  },
  {
    section: "Entertainment",
    numb: 56,
    question: "What was the first feature-length animated movie ever released?",
    answer: "Snow White and the Seven Dwarfs",
    options: ["Snow White and the Seven Dwarfs", "Pinocchio", "Dumbo", "Bambi"],
  },
  {
    section: "Entertainment",
    numb: 57,
    question: "In The Matrix, does Neo take the blue pill or the red pill?",
    answer: "Red",
    options: ["Blue", "Green", "Yellow", "Red"],
  },
  {
    section: "Entertainment",
    numb: 58,
    question: "Who played Juror Number 8 in 12 Angry Men?",
    answer: "Henry Fonda",
    options: ["Gregory Peck", "Henry Fonda", "Marlon Brando", "James Stewart"],
  },
  {
    section: "Entertainment",
    numb: 59,
    question: "Which movie won the first Academy Award for Best Picture?",
    answer: "Wings",
    options: ["Wings", "Sunrise", "The Jazz Singer", "Metropolis"],
  },
  {
    section: "Entertainment",
    numb: 60,
    question: "Who directed the movie 'Titanic'?",
    answer: "James Cameron",
    options: [
      "Steven Spielberg",
      "George Lucas",
      "James Cameron",
      "Martin Scorsese",
    ],
  },
];
